name: trail
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  get: ^4.6.1 
  dartz: ^0.10.1
  # For Immutable List
  # kt_dart: ^0.10.0
  freezed_annotation: ^0.14.1
  # file_picker: ^4.2.7
  json_annotation: ^4.3.0
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  firebase_storage: ^10.2.4
  cloud_firestore: ^3.1.5
  multi_image_picker2: ^5.0.2
  # shared_preferences: ^2.0.11
  rounded_loading_button: ^2.0.9
  # uuid: ^3.0.5
  firebase_crashlytics: ^2.4.5
  # for converting asset to file
  # for adding images to fire storage
  # flutter_absolute_path: ^1.0.6
  rxdart: ^0.27.3
  carousel_slider: ^4.0.0
  flutterfire_ui: ^0.3.2
  # liquid_pull_to_refresh: ^3.0.1
  pull_to_refresh: ^2.0.0
  material_floating_search_bar: ^0.3.6
  # extended_image: ^6.0.1
  cached_network_image: ^3.2.0
  # timeago: ^3.2.1
  flutter_absolute_path:
   git:
    url: https://github.com/kornperkus/flutter_absolute_path.git
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: 
  freezed: ^0.14.1+1
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true  
  assets: 
     - assets/